### ISSUE TITLE
json_number does not prevent unexpected stringification before encoding

### ISSUE THREAD

**Issue by oschwald** [maxmind/JSON-XS-Sugar-perl#2]
For example:

```
my $hash = {num => json_number(1)};
$hash->{num} eq '1';
say encode_json($hash);
```

Outputs:

```
{"num":"1"}
```

**Comment by 2shortplanks** [comment]
Yeah, that's a limitation of Perl that goes beyond the scope of what I can
do in this module without changing the underlying implementation of
JSON::XS. Ideally you'd use some sort of magic to provide a more
nonvolatile metadata which the underlying JSON encoder would know to look
at and interpret.

Right now I suspect the best thing to do is document this limitation in the
module's pod

**Comment by oschwald** [comment]
Potentially it could work with with a numeric-like object and enabling `convert_blessed` in JSON::XS. That object could even be a blessed scalar ref of the number to make it very lightweight.

**Comment by oschwald** [comment]
An even easier solution that doesn't involve any objects would be to make the number read-only using `SvREADONLY_on`. I don't think this would have any surprising consequences for a number value, and it prevents the string from being added to the SV.

Edit: I'm not sure this works. A tied variable might work though.

**Comment by 2shortplanks** [comment]
Yeah, the SvREADONLY_on doesn't work.

```
perl -e 'use Scalar::Readonly qw(readonly_on); my $foo = 3; readonly_on $foo; use Devel::Peek; Dump $foo; $bar = $foo.""; Dump $foo'
SV = IV(0x7fce19812540) at 0x7fce19812550
  REFCNT = 1
  FLAGS = (PADMY,IOK,READONLY,pIOK)
  IV = 3
SV = PVIV(0x7fce19814620) at 0x7fce19812550
  REFCNT = 1
  FLAGS = (PADMY,IOK,POK,READONLY,pIOK,pPOK)
  IV = 3
  PV = 0x7fce1940afb0 "3"\0
  CUR = 1
  LEN = 16

```

Overloaded objects might be the way to go, and require `convert_blessed` to be enabled.  I'm not sure there's not a solution with some other form of magic that might be useful here (see Variable::Magic for ideas of what's possible.)  I'll think about this more tomorrow.

**Comment by 2shortplanks** [comment]
So, I was looking at what can be done with magic:

``` perl
#!/usr/bin/perl

use 5.014;
use warnings;

use Variable::Magic qw(wizard cast);
use JSON::XS qw(encode_json);

my $ridcully = wizard(
    get => sub { ${ $_[0] } = ${ $_[0] } + 0 },
);

{
    my $foo = 100;
    my $bar = $foo."";
    say "without wizard: ".encode_json({ foo => $foo });
}

{
    my $foo = 100;
    cast $foo, $ridcully;
    my $bar = $foo."";
    say "with wizard: ".encode_json({ foo => $foo });
}

__END__

without wizard: {"foo":"100"}
with wizard: {"foo":100}
```

While this looks promising, this magic is actually being applied to the variable $foo, meaning that once it's copied the magic is lost (unlike, say, overloading, where the special behavior is bound up in the variable itself)

I'll give it some more thought

**Comment by oschwald** [comment]
Closing as we no longer use this module.
